# Site settings
title: Daniel Wiesendorf
email: daniel@wiesendorf.net
description: "A Webdevs and Opensource Lovers Webiste to show off skills and opinion"
baseurl: ""
url: "http://wiesendorf.net"

#Socialmedia settings
github_username:    "wiesendaniel"
twitter_username:   "wiesendaniel"
facebook_username:  "wiesendorf"
gplus_username:     "wiesendaniel"

# Build settings
markdown: kramdown # or rdiscount
markdown_ext:  markdown, mkdown, mkdn, mkd, md
permalink: pretty


# Asset settings
sass:
    sass_dir: _sass
    style:   :compressed

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ["README.md", "CNAME"]

timezone: Europe/Berlin
encoding: utf-8